# Generated by Django 3.0.2 on 2020-01-17 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='movie',
            new_name='hotstar',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='movie_link',
            new_name='hotstar_link',
        ),
    ]
