# Generated by Django 3.0.2 on 2020-01-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20200117_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='hotstar_link',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='data',
            name='hotstar',
        ),
        migrations.AddField(
            model_name='data',
            name='provider',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
