# Generated by Django 3.0.3 on 2020-03-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20200118_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
